### ISSUE TITLE
Time error

### ISSUE THREAD

**Issue by hugo-pires** [ZeevG/python-forecast.io#28]
Hello

When I make a load forecast like this

    api_key = "xxxx"
    lat = xxxx
    lng = xxxx
    time = "2015-01-06 12:00:00"
    forecast = forecastio.load_forecast(api_key, lat, lng, time)

python returns the following error

    'str' object has no attribute 'timetuple'

Could you help me?

**Comment by ZeevG** [comment]
Hi, the time parameter needs to be a Python datetime object.

For example

```python
import datetime

api_key = "xxxx"
lat = xxxx
lng = xxxx
time = datetime.datetime(2015, 01, 06, 12, 0)
forecast = forecastio.load_forecast(api_key, lat, lng, time)
```

You can read up on datetime objects here https://docs.python.org/2/library/datetime.html#datetime-objects
