### ISSUE TITLE
Forecast __unicode__ attribute error

### ISSUE THREAD

**Issue by pvangundy** [ZeevG/python-forecast.io#37]
I'm running into an issue, whether I use forecastio with 2.7 or 3.4, where I'm getting the following error:

<code>AttributeError: "'Forecast' object has no attribute '__unicode__'"</code>

Not sure what I'm doing wrong or if this is a legit bug. Thanks in advance!

**Comment by pvangundy** [comment]
This is a user error. My bad.

**Comment by dharamsk** [comment]
well now I feel really stupid. I'm running into the same error. What was the fix?

**Comment by s-ravuri** [comment]
can anyone give a definitive answer for what to do here?

**Comment by Olive00000** [comment]
This part is neccecary:

forecast = forecastio.load_forecast(api_key, lat, lng)
byHour = forecast.hourly() #Can either put currently, minutely, hourly or daily
print (byHour.summary)
