### ISSUE TITLE
not downloading on raspberry pi (raspbian) 

### ISSUE THREAD

**Issue by bman46** [ZeevG/python-forecast.io#39]
entered the command sudo pip install python-forecastio in to terminal and it come out with this: (yes i do have PIP) 

-------------------------------------

pi@raspberrypi ~ $ sudo pip install python-forecastio
Downloading/unpacking python-forecastio
  Running setup.py egg_info for package python-forecastio
    
Downloading/unpacking requests>=1.6 (from python-forecastio)
  Running setup.py egg_info for package requests
    
Downloading/unpacking responses (from python-forecastio)
  Running setup.py egg_info for package responses
    No handlers could be found for logger "__main__"
    
Downloading/unpacking cookies (from responses->python-forecastio)
  Running setup.py egg_info for package cookies
    
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from responses->python-forecastio)
Downloading/unpacking mock (from responses->python-forecastio)
  Running setup.py egg_info for package mock
    mock requires setuptools>=17.1. Aborting installation
    Complete output from command python setup.py egg_info:
    mock requires setuptools>=17.1. Aborting installation

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/mock
Storing complete log in /root/.pip/pip.log

**Comment by ZeevG** [comment]
Looks like you might need to update setuptools

>mock requires setuptools>=17.1. Aborting installation

What version of setuptools do you have installed?
Also, what version of Python do you have installed?

**Comment by bman46** [comment]
I have the 3.0 and 2.5 version of python 
I have setup tools version 0.6.24dev-ro

**Comment by j1fig** [comment]
@bman46 I had a similar issue (though not on rPI) and I do this before running the `pip install`

    wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python

This script will install the freshest setuptools version.

Best,
Joao

**Comment by bman46** [comment]
Ok thanks I'll try it

**Comment by ZeevG** [comment]
Thanks for the suggestion. How did it go? You may also have to update
Python itself. This package is tested against Python 2.7 and 3.3 it may
work with other versions although I doubt it will be compatible with less
than 2.7

**Comment by bman46** [comment]
that fixed it. thanks sooooo much @j1fig
Note: i had to use super user to use the command but it worked

**Comment by j1fig** [comment]
Hi @bman46 , glad it worked ;)

From the initial problem, you mentioned that this problem appeared while running `sudo pip install` (super user), so I guess it's installing these packages to the system, and using the system's setuptools version (so this is the one being used by your command). 

However if you create a virtualenv and run the command I mentioned, followed by a `pip install`, it won't required super user (at least it doesn't for me)!

Best,
Joao

**Comment by bman46** [comment]
@J1fig for some reason it did for me and sudo was not enough it kept failing due to permissions until I used super user and then it worked its probably a permission error on my system

**Comment by bman46** [comment]
@J1fig also on Rpi I looked at the website and sudo does have some security blocks and super user does not

**Comment by borazslo** [comment]
I had the same problem on Raspberry Pi. For me this helped:
` sudo pip install -U setuptools`

**Comment by ZeevG** [comment]
Thanks for all the help with this. Unless there is something I can do to improve compatibility with Paspberry Pi's, I'm going to close this issue.
