### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by dharamsk** [ZeevG/python-forecast.io#43]
Hey, 

This is super useful and I love it. Had to install manually as pip install couldn't find a matching package. When I searched for it, it recommended python-forcastio (<--that's not a typo), but said there was no matching version for pypi to install.

**Comment by dharamsk** [comment]
work around for running on remote server:
export PYTHONPATH=$PYTHONPATH:/home/[_insert-your-user-name-here_]/.local/lib/python2.7/site-packages/
python setup.py install --user (_must run from within directory of the module_)

**Comment by ZeevG** [comment]
Hey, thanks for reporting this.
How did you try to install the package and what version of Python were you using?

**Comment by dharamsk** [comment]
Python 2.7.10

Tried:
"pip install forecastio" - not found
"pip install python-forcastio" - no matching version found

MacBook-Pro:analyst_bot dharamkhalsa$ pip install forecastio
Collecting forecastio
  Could not find a version that satisfies the requirement forecastio (from
versions: )
No matching distribution found for forecastio

*Dharam Khalsa*

**Comment by dharamsk** [comment]
Zeev - this was user error. For whatever reason I never tried `pip install python-forecastio`, which works.

Wishing I had never installed conda :/ finding more and more reasons not to use it.
