### ISSUE TITLE
alerts not functioning correctly

### ISSUE THREAD

**Issue by postables** [ZeevG/python-forecast.io#52]
alerts doesn't appear to function correctly
.>>> forecast = forecastio.load_forecast(api_key, lat, long)
.>>> alerts = forecast.alerts()
.>>> alerts
[]

**Comment by ZeevG** [comment]
Hi. There won't always be weather alerts and so sometimes that list is empty. This is from the Dark Sky docs

An alerts array, which, if present, contains any severe weather alerts pertinent to the requested location.

You can read more about alerts here https://darksky.net/dev/docs/response#alerts
