### ISSUE TITLE
Fix simple typo: caerful -> careful

### ISSUE THREAD

**Issue by timgates42** [ZeevG/python-forecast.io#68]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine README.rst.
2. Search for `caerful`.

# Expected Behaviour

1. Should read `careful`.

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/python-forecast.io/pull/new/bugfix_typo_careful

Thanks.

**Comment by wcdawn** [comment]
@timgates42 I don't know if you're just experimenting but this repo has been stale for 3 years and is an interface for a web API that no longer exists. You may want to include a check in your tool to see if the repo is effectively dead.

**Comment by timgates42** [comment]
Thanks @wcdawn I ignore archived GitHub repositories - is that an option to archive this GitHub repository?
